name: Niche Media
favicon: null
layout_spectrum: 0.8744054432027042
typography_spectrum: 0.21328863315284252
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6436206873040646
  lightness: 0.8495696706231683
  saturation: 0.2550873428117484
  rhythmicContrast: 0.33522556023672223
purpose: []
